image: php:latest

before_script:
  - export NO_INTERACTION=1
  - apt-get -y update
  - apt-get -y install autoconf build-essential gcc g++ valgrind

php71:
  image: php:7.1
  stage: build
  script:
    - phpize
    - ./configure --enable-bencode
    - make -j$(nproc)
    - make test TESTS="-m"
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_PHP71"
    expire_in: 2 weeks
    paths:
      - modules/bencode.so

php72:
  image: php:7.2
  stage: build
  script:
    - phpize
    - ./configure --enable-bencode
    - make -j$(nproc)
    - make test TESTS="-m"
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_PHP72"
    expire_in: 2 weeks
    paths:
      - modules/bencode.so

php73:
  image: php:7.3
  stage: build
  script:
    - phpize
    - ./configure --enable-bencode
    - make -j$(nproc)
    - make test # TESTS="-m"
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_PHP73"
    expire_in: 2 weeks
    paths:
      - modules/bencode.so
