image: php:latest

before_script:
  - export NO_INTERACTION=1
  - apt-get -y update
  - apt-get -y upgrade
  - apt-get -y install autoconf build-essential gcc g++ valgrind

.php:
  stage: build
  except:
    - HEAD
  script:
    - phpize
    - ./configure --enable-bencode
    - make -j$(nproc)
    - chmod 600 ./.valgrindrc
    - make test TESTS="-m"
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    expire_in: 2 weeks
    paths:
      - modules/bencode.so

php81:
  extends: .php
  image: php:8.1

php80:
  extends: .php
  image: php:8.0

php74:
  extends: .php
  image: php:7.4

php73:
  extends: .php
  image: php:7.3
