image: php:latest

before_script:
  - export NO_INTERACTION=1
  - apt-get -y update
  - apt-get -y install autoconf build-essential gcc g++

build:
  stage: build
  script:
    - phpize
    - ./configure --enable-bencode
    - make -j$(nproc)
    - make test
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    expire_in: 2 weeks
    paths:
      - modules/bencode.so
