dist: trusty
sudo: required

language: php

addons:
    apt:
        sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
        packages:
            - autoconf
            - build-essential
            - gcc-5
            - g++-5

php:
  - '7.1'

before_install:
    - export CC=gcc-5
    - export CXX=g++-5
    - export NO_INTERACTION=1

script:
    - phpize
    - ./configure --enable-bencode
    - make -j$(nproc)
    - make test
