dist: bionic
sudo: required

language: php

addons:
  apt:
    packages:
      - autoconf
      - build-essential
      - valgrind

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

env:
  - NO_INTERACTION=1

script:
  - phpize
  - ./configure --enable-bencode
  - make -j$(nproc)
  - chmod 600 ./.valgrindrc
  - make test TESTS="-m"
