dist: trusty
sudo: required

language: cpp

addons:
    apt:
        sources:
            - sourceline: 'ppa:ondrej/php'
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
        packages:
            - php7.1-dev
            - autoconf
            - build-essential
            - gcc-5
            - g++-5

before_install:
    - export CC=gcc-5
    - export CXX=g++-5
    - export NO_INTERACTION=1

script:
    - dpkg -l | grep php
    - ls /usr/bin | grep php
    - phpize
    - ./configure --enable-bencode
    - make -j$(nproc)
    - make test
