dist: trusty
sudo: required

language: php

addons:
    apt:
        sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
        packages:
            - autoconf
            - build-essential
            - gcc-5
            - g++-5
            - valgrind

php:
  - '7.1'
  - '7.2'
  - '7.3'

before_install:
    - export CC=gcc-5
    - export CXX=g++-5
    - export NO_INTERACTION=1

script:
    - phpize
    - ./configure --enable-bencode
    - make -j$(nproc)
    - bash -c '[[ -z `php -v | grep "^PHP 7.3"` ]] && make test TESTS="-m" || make test'
